"""add associations

Revision ID: 032a770685e5
Revises: 00be8d7e6489
Create Date: 2025-11-17 22:40:35.742507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '032a770685e5'
down_revision: Union[str, Sequence[str], None] = '00be8d7e6489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('user_id', sa.UUID(), nullable=True))
    op.alter_column('candidates', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'candidates', 'users', ['user_id'], ['user_id'])
    op.add_column('resumes', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('resumes', sa.Column('company_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'company_id')
    op.drop_column('resumes', 'user_id')
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.alter_column('candidates', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('candidates', 'user_id')
    # ### end Alembic commands ###
