"""Add rejection fields

Revision ID: 81130f9841d5
Revises: b26cf666e6cc
Create Date: 2025-11-22 01:55:32.430595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81130f9841d5'
down_revision: Union[str, Sequence[str], None] = 'b26cf666e6cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('candidates_rejected_by_fkey'), 'candidates', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('candidates_rejected_by_fkey'), 'candidates', 'companies', ['rejected_by'], ['id'])
    # ### end Alembic commands ###
