"""Add rejection fields

Revision ID: b26cf666e6cc
Revises: 2dbab079d894
Create Date: 2025-11-22 01:48:52.572637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b26cf666e6cc'
down_revision: Union[str, Sequence[str], None] = '2dbab079d894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('rejected', sa.String(length=50), nullable=True))
    op.add_column('candidates', sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('candidates', sa.Column('rejected_by', sa.UUID(), nullable=True))
    op.add_column('candidates', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'candidates', 'companies', ['rejected_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_column('candidates', 'rejection_reason')
    op.drop_column('candidates', 'rejected_by')
    op.drop_column('candidates', 'rejected_at')
    op.drop_column('candidates', 'rejected')
    # ### end Alembic commands ###
