"""Add contact_person

Revision ID: d504bd6e91d9
Revises: 7979d2a59b1f
Create Date: 2025-11-27 00:00:45.556728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd504bd6e91d9'
down_revision: Union[str, Sequence[str], None] = '7979d2a59b1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('contact_person', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'contact_person')
    # ### end Alembic commands ###
