"""added created_by in shortlist

Revision ID: f92d8af184cc
Revises: 81130f9841d5
Create Date: 2025-11-22 06:56:38.437059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f92d8af184cc'
down_revision: Union[str, Sequence[str], None] = '81130f9841d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shortlist', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shortlist', 'created_at')
    # ### end Alembic commands ###
